### ISSUE TITLE
Meltdown / Spectre mitigation needed

### ISSUE THREAD

**Issue by afaerber** [MarvellEmbeddedProcessors/atf-marvell#5]
While issue #4 promised an update to ATF v1.4 for February, the Meltdown / Spectre vulnerabilities disclosed this week require security fixes for Cortex-A72.

Do you plan to accelerate that forward-port now, or will you be backporting the fixes from ARM-software/arm-trusted-firmware#1214 to the old code base? Thanks.

**Comment by haklai** [comment]
ARM ATF fixes were backported and merged in:
https://github.com/MarvellEmbeddedProcessors/atf-marvell/commits/atf-v1.3-armada-17.10

**Comment by afaerber** [comment]
@haklai Are you planning to also backport the workaround serial output and SMCCC v1.1 for detecting the mitigations?

**Comment by kostapr** [comment]
We have merged this patch:
https://github.com/ARM-software/arm-trusted-firmware/pull/1214/commits/f62ad322695d16178db464dc062fe0af592c6780
and skipped the second patch (since we do not have CA73/CA75 based platforms):
https://github.com/ARM-software/arm-trusted-firmware/pull/1214/commits/a1781a211a53df6a24345d774c0f2eaa5b675ca8
I have found that the third patch is probably applicable too, but must be back-ported.
I will handle this right now.
Regarding the SMCCC v1.1 and workaround serial output - could you please point to the relevant patches in the mainline?

**Comment by kostapr** [comment]
I must correct myself - the third patch is also not applicable to our platforms since it's CA75-related:
https://github.com/ARM-software/arm-trusted-firmware/pull/1214/commits/780edd86a0b413c3620c5c42fd123a78b5b1587a

**Comment by afaerber** [comment]
Those three commits are all from the first pull request. There are at least two more pull requests for Spectre upstream, in addition to the one you have cherry-picked from. The 32-bit pull request contains two commits for serial output, and another pull request optimized the initial mitigation and added SMCCC v1.1 with discovery support for the mitigations.

**Comment by kostapr** [comment]
I see. So 32-bit changes (CA9/CA15/CA17) are not applicable to Marvell platforms - we only have aarch64 support:
https://github.com/ARM-software/arm-trusted-firmware/pull/1228
I have to review the third pull request in terms of applicability to our platforms:
https://github.com/ARM-software/arm-trusted-firmware/pull/1240

**Comment by afaerber** [comment]
My point was, the first two commits of ARM-software/arm-trusted-firmware#1228 have nothing to do with AArch32 and should please be included for diagnostics, too.

**Comment by kostapr** [comment]
Got you. I will review these patches and backport them if needed.
